/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionFlowRouteImport } from './routes/transaction-flow'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OfficerReviewRouteImport } from './routes/officer-review'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const TransactionFlowRoute = TransactionFlowRouteImport.update({
  id: '/transaction-flow',
  path: '/transaction-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerReviewRoute = OfficerReviewRouteImport.update({
  id: '/officer-review',
  path: '/officer-review',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/investigation': typeof InvestigationRoute
  '/officer-review': typeof OfficerReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transaction-flow': typeof TransactionFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/investigation': typeof InvestigationRoute
  '/officer-review': typeof OfficerReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transaction-flow': typeof TransactionFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/investigation': typeof InvestigationRoute
  '/officer-review': typeof OfficerReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transaction-flow': typeof TransactionFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/alerts'
    | '/cases'
    | '/graph'
    | '/investigation'
    | '/officer-review'
    | '/reports'
    | '/settings'
    | '/transaction-flow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/alerts'
    | '/cases'
    | '/graph'
    | '/investigation'
    | '/officer-review'
    | '/reports'
    | '/settings'
    | '/transaction-flow'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/alerts'
    | '/cases'
    | '/graph'
    | '/investigation'
    | '/officer-review'
    | '/reports'
    | '/settings'
    | '/transaction-flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRoute
  GraphRoute: typeof GraphRoute
  InvestigationRoute: typeof InvestigationRoute
  OfficerReviewRoute: typeof OfficerReviewRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionFlowRoute: typeof TransactionFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction-flow': {
      id: '/transaction-flow'
      path: '/transaction-flow'
      fullPath: '/transaction-flow'
      preLoaderRoute: typeof TransactionFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer-review': {
      id: '/officer-review'
      path: '/officer-review'
      fullPath: '/officer-review'
      preLoaderRoute: typeof OfficerReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRoute,
  GraphRoute: GraphRoute,
  InvestigationRoute: InvestigationRoute,
  OfficerReviewRoute: OfficerReviewRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TransactionFlowRoute: TransactionFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
