# Risk thresholds
ONBOARDING_BLOCK_THRESHOLD = 85
TRANSACTION_BLOCK_THRESHOLD = 90

# Compliance limits (India AML context)
UPI_LIMIT = 100000
NEW_USER_LIMIT = 5000

# Risk labels
RISK_LOW = "LOW"
RISK_MEDIUM = "MEDIUM"
RISK_HIGH = "HIGH"
RISK_CRITICAL = "CRITICAL"